services:
  scheduler-app:
    image: projetudsp38/udsp38-scheduler-microservice:latest
    container_name: udsp38-scheduler-ms-prod
    restart: always
    ports:
      - "8000:8000"
    networks:
      - reseau-apps-test

networks:
  reseau-apps-test: