services:
  scheduler-app:
    image: projetudsp38/udsp38-scheduler-microservice:latest
    container_name: udsp38-scheduler-ms-prod
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - reseau-apps-prod

networks:
  reseau-apps-prod:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450