services:
  scheduler-app:
    image: projetudsp38/udsp38-scheduler-microservice:test
    container_name: udsp38-scheduler-ms-test
    restart: always
    network_mode: "host"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - reseau-apps-test

networks:
  reseau-apps-test:
    external: true