services:
  scheduler-app:
    image: projetudsp38/udsp38-scheduler-microservice:latest
    container_name: udsp38-scheduler-ms-prod
    restart: always
    volumes:
      - /opt/udsp38-app/scheduler-microservice/.env.prod:/app/.env
    ports:
      - "8000:8000"
    networks:
      - reseau-apps-prod

networks:
  reseau-apps-prod:
    name: reseau-apps-prod
    driver: bridge
    external: true