services:
  scheduler-app:
    image: projetudsp38/udsp38-scheduler-microservice:test
    container_name: udsp38-scheduler-ms-test
    restart: always
    networks:
      - reseau-apps-test

networks:
  reseau-apps-test:
    external: true